<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8qeeQtT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8qeeQtT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8qeeQtT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8qeeQtT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8qeeQtT\App_KernelDevDebugContainer([
    'container.build_hash' => '8qeeQtT',
    'container.build_id' => '4346f80e',
    'container.build_time' => 1638982083,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8qeeQtT');
